#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt_do_rzezni
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Rzeznia")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertfirma(firma instance);
    partial void Updatefirma(firma instance);
    partial void Deletefirma(firma instance);
    partial void Insertinwentarz(inwentarz instance);
    partial void Updateinwentarz(inwentarz instance);
    partial void Deleteinwentarz(inwentarz instance);
    partial void Insertlokalizacja(lokalizacja instance);
    partial void Updatelokalizacja(lokalizacja instance);
    partial void Deletelokalizacja(lokalizacja instance);
    partial void Insertpartia(partia instance);
    partial void Updatepartia(partia instance);
    partial void Deletepartia(partia instance);
    partial void Insertpodzial_tuszy_miesa(podzial_tuszy_miesa instance);
    partial void Updatepodzial_tuszy_miesa(podzial_tuszy_miesa instance);
    partial void Deletepodzial_tuszy_miesa(podzial_tuszy_miesa instance);
    partial void Insertpracownik(pracownik instance);
    partial void Updatepracownik(pracownik instance);
    partial void Deletepracownik(pracownik instance);
    partial void Insertstanowisko(stanowisko instance);
    partial void Updatestanowisko(stanowisko instance);
    partial void Deletestanowisko(stanowisko instance);
    partial void Insertzamowienie(zamowienie instance);
    partial void Updatezamowienie(zamowienie instance);
    partial void Deletezamowienie(zamowienie instance);
    partial void Insertzwierze_gatunek(zwierze_gatunek instance);
    partial void Updatezwierze_gatunek(zwierze_gatunek instance);
    partial void Deletezwierze_gatunek(zwierze_gatunek instance);
    partial void Insertzwierzyna(zwierzyna instance);
    partial void Updatezwierzyna(zwierzyna instance);
    partial void Deletezwierzyna(zwierzyna instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::projekt_do_rzezni.Properties.Settings.Default.RzezniaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<firma> firmas
		{
			get
			{
				return this.GetTable<firma>();
			}
		}
		
		public System.Data.Linq.Table<inwentarz> inwentarzs
		{
			get
			{
				return this.GetTable<inwentarz>();
			}
		}
		
		public System.Data.Linq.Table<lokalizacja> lokalizacjas
		{
			get
			{
				return this.GetTable<lokalizacja>();
			}
		}
		
		public System.Data.Linq.Table<partia> partias
		{
			get
			{
				return this.GetTable<partia>();
			}
		}
		
		public System.Data.Linq.Table<partia_zwierzyna> partia_zwierzynas
		{
			get
			{
				return this.GetTable<partia_zwierzyna>();
			}
		}
		
		public System.Data.Linq.Table<podzial_tuszy_miesa> podzial_tuszy_miesas
		{
			get
			{
				return this.GetTable<podzial_tuszy_miesa>();
			}
		}
		
		public System.Data.Linq.Table<pracownik> pracowniks
		{
			get
			{
				return this.GetTable<pracownik>();
			}
		}
		
		public System.Data.Linq.Table<stanowisko> stanowiskos
		{
			get
			{
				return this.GetTable<stanowisko>();
			}
		}
		
		public System.Data.Linq.Table<zamowienie> zamowienies
		{
			get
			{
				return this.GetTable<zamowienie>();
			}
		}
		
		public System.Data.Linq.Table<zwierze_gatunek> zwierze_gatuneks
		{
			get
			{
				return this.GetTable<zwierze_gatunek>();
			}
		}
		
		public System.Data.Linq.Table<zwierze_rodzaje_miesa> zwierze_rodzaje_miesas
		{
			get
			{
				return this.GetTable<zwierze_rodzaje_miesa>();
			}
		}
		
		public System.Data.Linq.Table<zwierzyna> zwierzynas
		{
			get
			{
				return this.GetTable<zwierzyna>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.firma")]
	public partial class firma : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_firmy;
		
		private string _nazwa;
		
		private string _NIP;
		
		private string _telefon;
		
		private string _fax;
		
		private string _email;
		
		private int _lokalizacja;
		
		private EntitySet<inwentarz> _inwentarzs;
		
		private EntityRef<lokalizacja> _lokalizacja1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_firmyChanging(int value);
    partial void Onid_firmyChanged();
    partial void Onnazwa_firmyChanging(string value);
    partial void Onnazwa_firmyChanged();
    partial void OnNIPChanging(string value);
    partial void OnNIPChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnlokalizacjaChanging(int value);
    partial void OnlokalizacjaChanged();
    #endregion
		
		public firma()
		{
			this._inwentarzs = new EntitySet<inwentarz>(new Action<inwentarz>(this.attach_inwentarzs), new Action<inwentarz>(this.detach_inwentarzs));
			this._lokalizacja1 = default(EntityRef<lokalizacja>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_firmy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_firmy
		{
			get
			{
				return this._id_firmy;
			}
			set
			{
				if ((this._id_firmy != value))
				{
					this.Onid_firmyChanging(value);
					this.SendPropertyChanging();
					this._id_firmy = value;
					this.SendPropertyChanged("id_firmy");
					this.Onid_firmyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nazwa_firmy
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.Onnazwa_firmyChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa_firmy");
					this.Onnazwa_firmyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIP", DbType="Char(13) NOT NULL", CanBeNull=false)]
		public string NIP
		{
			get
			{
				return this._NIP;
			}
			set
			{
				if ((this._NIP != value))
				{
					this.OnNIPChanging(value);
					this.SendPropertyChanging();
					this._NIP = value;
					this.SendPropertyChanged("NIP");
					this.OnNIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lokalizacja", DbType="Int NOT NULL")]
		public int lokalizacja
		{
			get
			{
				return this._lokalizacja;
			}
			set
			{
				if ((this._lokalizacja != value))
				{
					if (this._lokalizacja1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlokalizacjaChanging(value);
					this.SendPropertyChanging();
					this._lokalizacja = value;
					this.SendPropertyChanged("lokalizacja");
					this.OnlokalizacjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="firma_inwentarz", Storage="_inwentarzs", ThisKey="id_firmy", OtherKey="dostawca")]
		public EntitySet<inwentarz> inwentarzs
		{
			get
			{
				return this._inwentarzs;
			}
			set
			{
				this._inwentarzs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lokalizacja_firma", Storage="_lokalizacja1", ThisKey="lokalizacja", OtherKey="id_lokalizacja", IsForeignKey=true)]
		public lokalizacja lokalizacja1
		{
			get
			{
				return this._lokalizacja1.Entity;
			}
			set
			{
				lokalizacja previousValue = this._lokalizacja1.Entity;
				if (((previousValue != value) 
							|| (this._lokalizacja1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lokalizacja1.Entity = null;
						previousValue.firmas.Remove(this);
					}
					this._lokalizacja1.Entity = value;
					if ((value != null))
					{
						value.firmas.Add(this);
						this._lokalizacja = value.id_lokalizacja;
					}
					else
					{
						this._lokalizacja = default(int);
					}
					this.SendPropertyChanged("lokalizacja1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_inwentarzs(inwentarz entity)
		{
			this.SendPropertyChanging();
			entity.firma = this;
		}
		
		private void detach_inwentarzs(inwentarz entity)
		{
			this.SendPropertyChanging();
			entity.firma = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.inwentarz")]
	public partial class inwentarz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_inwentarz;
		
		private int _zwierzyna;
		
		private int _dostawca;
		
		private System.DateTime _data_zakupu;
		
		private decimal _waga;
		
		private bool _kontrola;
		
		private EntityRef<firma> _firma;
		
		private EntityRef<zwierzyna> _zwierzyna1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_inwentarzChanging(int value);
    partial void Onid_inwentarzChanged();
    partial void OnzwierzynaChanging(int value);
    partial void OnzwierzynaChanged();
    partial void OndostawcaChanging(int value);
    partial void OndostawcaChanged();
    partial void Ondata_zakupuChanging(System.DateTime value);
    partial void Ondata_zakupuChanged();
    partial void OnwagaChanging(decimal value);
    partial void OnwagaChanged();
    partial void OnkontrolaChanging(bool value);
    partial void OnkontrolaChanged();
    #endregion
		
		public inwentarz()
		{
			this._firma = default(EntityRef<firma>);
			this._zwierzyna1 = default(EntityRef<zwierzyna>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_inwentarz", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_inwentarz
		{
			get
			{
				return this._id_inwentarz;
			}
			set
			{
				if ((this._id_inwentarz != value))
				{
					this.Onid_inwentarzChanging(value);
					this.SendPropertyChanging();
					this._id_inwentarz = value;
					this.SendPropertyChanged("id_inwentarz");
					this.Onid_inwentarzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zwierzyna", DbType="Int NOT NULL")]
		public int zwierzyna
		{
			get
			{
				return this._zwierzyna;
			}
			set
			{
				if ((this._zwierzyna != value))
				{
					if (this._zwierzyna1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnzwierzynaChanging(value);
					this.SendPropertyChanging();
					this._zwierzyna = value;
					this.SendPropertyChanged("zwierzyna");
					this.OnzwierzynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dostawca", DbType="Int NOT NULL")]
		public int dostawca
		{
			get
			{
				return this._dostawca;
			}
			set
			{
				if ((this._dostawca != value))
				{
					if (this._firma.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OndostawcaChanging(value);
					this.SendPropertyChanging();
					this._dostawca = value;
					this.SendPropertyChanged("dostawca");
					this.OndostawcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_zakupu", DbType="Date NOT NULL")]
		public System.DateTime data_zakupu
		{
			get
			{
				return this._data_zakupu;
			}
			set
			{
				if ((this._data_zakupu != value))
				{
					this.Ondata_zakupuChanging(value);
					this.SendPropertyChanging();
					this._data_zakupu = value;
					this.SendPropertyChanged("data_zakupu");
					this.Ondata_zakupuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_waga", DbType="Decimal(9,3) NOT NULL")]
		public decimal waga
		{
			get
			{
				return this._waga;
			}
			set
			{
				if ((this._waga != value))
				{
					this.OnwagaChanging(value);
					this.SendPropertyChanging();
					this._waga = value;
					this.SendPropertyChanged("waga");
					this.OnwagaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kontrola", DbType="Bit NOT NULL")]
		public bool kontrola
		{
			get
			{
				return this._kontrola;
			}
			set
			{
				if ((this._kontrola != value))
				{
					this.OnkontrolaChanging(value);
					this.SendPropertyChanging();
					this._kontrola = value;
					this.SendPropertyChanged("kontrola");
					this.OnkontrolaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="firma_inwentarz", Storage="_firma", ThisKey="dostawca", OtherKey="id_firmy", IsForeignKey=true)]
		public firma firma
		{
			get
			{
				return this._firma.Entity;
			}
			set
			{
				firma previousValue = this._firma.Entity;
				if (((previousValue != value) 
							|| (this._firma.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._firma.Entity = null;
						previousValue.inwentarzs.Remove(this);
					}
					this._firma.Entity = value;
					if ((value != null))
					{
						value.inwentarzs.Add(this);
						this._dostawca = value.id_firmy;
					}
					else
					{
						this._dostawca = default(int);
					}
					this.SendPropertyChanged("firma");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="zwierzyna_inwentarz", Storage="_zwierzyna1", ThisKey="zwierzyna", OtherKey="id_zwierzyna", IsForeignKey=true)]
		public zwierzyna zwierzyna1
		{
			get
			{
				return this._zwierzyna1.Entity;
			}
			set
			{
				zwierzyna previousValue = this._zwierzyna1.Entity;
				if (((previousValue != value) 
							|| (this._zwierzyna1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._zwierzyna1.Entity = null;
						previousValue.inwentarzs.Remove(this);
					}
					this._zwierzyna1.Entity = value;
					if ((value != null))
					{
						value.inwentarzs.Add(this);
						this._zwierzyna = value.id_zwierzyna;
					}
					else
					{
						this._zwierzyna = default(int);
					}
					this.SendPropertyChanged("zwierzyna1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lokalizacja")]
	public partial class lokalizacja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_lokalizacja;
		
		private string _miasto;
		
		private string _kraj;
		
		private string _adres;
		
		private string _kod_pocztowy;
		
		private EntitySet<firma> _firmas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_lokalizacjaChanging(int value);
    partial void Onid_lokalizacjaChanged();
    partial void OnmiastoChanging(string value);
    partial void OnmiastoChanged();
    partial void OnkrajChanging(string value);
    partial void OnkrajChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void Onkod_pocztowyChanging(string value);
    partial void Onkod_pocztowyChanged();
    #endregion
		
		public lokalizacja()
		{
			this._firmas = new EntitySet<firma>(new Action<firma>(this.attach_firmas), new Action<firma>(this.detach_firmas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lokalizacja", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_lokalizacja
		{
			get
			{
				return this._id_lokalizacja;
			}
			set
			{
				if ((this._id_lokalizacja != value))
				{
					this.Onid_lokalizacjaChanging(value);
					this.SendPropertyChanging();
					this._id_lokalizacja = value;
					this.SendPropertyChanged("id_lokalizacja");
					this.Onid_lokalizacjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miasto", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string miasto
		{
			get
			{
				return this._miasto;
			}
			set
			{
				if ((this._miasto != value))
				{
					this.OnmiastoChanging(value);
					this.SendPropertyChanging();
					this._miasto = value;
					this.SendPropertyChanged("miasto");
					this.OnmiastoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kraj", DbType="VarChar(50)")]
		public string kraj
		{
			get
			{
				return this._kraj;
			}
			set
			{
				if ((this._kraj != value))
				{
					this.OnkrajChanging(value);
					this.SendPropertyChanging();
					this._kraj = value;
					this.SendPropertyChanged("kraj");
					this.OnkrajChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod_pocztowy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string kod_pocztowy
		{
			get
			{
				return this._kod_pocztowy;
			}
			set
			{
				if ((this._kod_pocztowy != value))
				{
					this.Onkod_pocztowyChanging(value);
					this.SendPropertyChanging();
					this._kod_pocztowy = value;
					this.SendPropertyChanged("kod_pocztowy");
					this.Onkod_pocztowyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lokalizacja_firma", Storage="_firmas", ThisKey="id_lokalizacja", OtherKey="lokalizacja")]
		public EntitySet<firma> firmas
		{
			get
			{
				return this._firmas;
			}
			set
			{
				this._firmas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_firmas(firma entity)
		{
			this.SendPropertyChanging();
			entity.lokalizacja1 = this;
		}
		
		private void detach_firmas(firma entity)
		{
			this.SendPropertyChanging();
			entity.lokalizacja1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.partia")]
	public partial class partia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_partii;
		
		private System.DateTime _data;
		
		private string _kod;
		
		private EntityRef<zamowienie> _zamowienie;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_partiiChanging(int value);
    partial void Onid_partiiChanged();
    partial void OndataChanging(System.DateTime value);
    partial void OndataChanged();
    partial void OnkodChanging(string value);
    partial void OnkodChanged();
    #endregion
		
		public partia()
		{
			this._zamowienie = default(EntityRef<zamowienie>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_partii", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_partii
		{
			get
			{
				return this._id_partii;
			}
			set
			{
				if ((this._id_partii != value))
				{
					if (this._zamowienie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_partiiChanging(value);
					this.SendPropertyChanging();
					this._id_partii = value;
					this.SendPropertyChanged("id_partii");
					this.Onid_partiiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="Date NOT NULL")]
		public System.DateTime data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kod", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string kod
		{
			get
			{
				return this._kod;
			}
			set
			{
				if ((this._kod != value))
				{
					this.OnkodChanging(value);
					this.SendPropertyChanging();
					this._kod = value;
					this.SendPropertyChanged("kod");
					this.OnkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="zamowienie_partia", Storage="_zamowienie", ThisKey="id_partii", OtherKey="id_zamowienie", IsForeignKey=true)]
		public zamowienie zamowienie
		{
			get
			{
				return this._zamowienie.Entity;
			}
			set
			{
				zamowienie previousValue = this._zamowienie.Entity;
				if (((previousValue != value) 
							|| (this._zamowienie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._zamowienie.Entity = null;
						previousValue.partia = null;
					}
					this._zamowienie.Entity = value;
					if ((value != null))
					{
						value.partia = this;
						this._id_partii = value.id_zamowienie;
					}
					else
					{
						this._id_partii = default(int);
					}
					this.SendPropertyChanged("zamowienie");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.partia_zwierzyna")]
	public partial class partia_zwierzyna
	{
		
		private int _id_partii;
		
		private int _id_zwierzyny;
		
		public partia_zwierzyna()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_partii", DbType="Int NOT NULL")]
		public int id_partii
		{
			get
			{
				return this._id_partii;
			}
			set
			{
				if ((this._id_partii != value))
				{
					this._id_partii = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_zwierzyny", DbType="Int NOT NULL")]
		public int id_zwierzyny
		{
			get
			{
				return this._id_zwierzyny;
			}
			set
			{
				if ((this._id_zwierzyny != value))
				{
					this._id_zwierzyny = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.podzial_tuszy_miesa")]
	public partial class podzial_tuszy_miesa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_gatunek;
		
		private string _nazwa;
		
		private decimal _cena;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_gatunekChanging(int value);
    partial void Onid_gatunekChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void OncenaChanging(decimal value);
    partial void OncenaChanged();
    #endregion
		
		public podzial_tuszy_miesa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_gatunek", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_gatunek
		{
			get
			{
				return this._id_gatunek;
			}
			set
			{
				if ((this._id_gatunek != value))
				{
					this.Onid_gatunekChanging(value);
					this.SendPropertyChanging();
					this._id_gatunek = value;
					this.SendPropertyChanged("id_gatunek");
					this.Onid_gatunekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cena", DbType="Money NOT NULL")]
		public decimal cena
		{
			get
			{
				return this._cena;
			}
			set
			{
				if ((this._cena != value))
				{
					this.OncenaChanging(value);
					this.SendPropertyChanging();
					this._cena = value;
					this.SendPropertyChanged("cena");
					this.OncenaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pracownik")]
	public partial class pracownik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pracownik;
		
		private string _imie;
		
		private string _nazwisko;
		
		private string _pesel;
		
		private int _stanowisko;
		
		private System.DateTime _data_urodzenia;
		
		private string _lokalizacja;
		
		private string _telefon;
		
		private System.DateTime _data_przyjecia;
		
		private EntityRef<stanowisko> _stanowisko1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pracownikChanging(int value);
    partial void Onid_pracownikChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void OnpeselChanging(string value);
    partial void OnpeselChanged();
    partial void OnstanowiskoChanging(int value);
    partial void OnstanowiskoChanged();
    partial void Ondata_urodzeniaChanging(System.DateTime value);
    partial void Ondata_urodzeniaChanged();
    partial void OnlokalizacjaChanging(string value);
    partial void OnlokalizacjaChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void Ondata_przyjeciaChanging(System.DateTime value);
    partial void Ondata_przyjeciaChanged();
    #endregion
		
		public pracownik()
		{
			this._stanowisko1 = default(EntityRef<stanowisko>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pracownik", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pracownik
		{
			get
			{
				return this._id_pracownik;
			}
			set
			{
				if ((this._id_pracownik != value))
				{
					this.Onid_pracownikChanging(value);
					this.SendPropertyChanging();
					this._id_pracownik = value;
					this.SendPropertyChanged("id_pracownik");
					this.Onid_pracownikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesel", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string pesel
		{
			get
			{
				return this._pesel;
			}
			set
			{
				if ((this._pesel != value))
				{
					this.OnpeselChanging(value);
					this.SendPropertyChanging();
					this._pesel = value;
					this.SendPropertyChanged("pesel");
					this.OnpeselChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stanowisko", DbType="Int NOT NULL")]
		public int stanowisko
		{
			get
			{
				return this._stanowisko;
			}
			set
			{
				if ((this._stanowisko != value))
				{
					if (this._stanowisko1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstanowiskoChanging(value);
					this.SendPropertyChanging();
					this._stanowisko = value;
					this.SendPropertyChanged("stanowisko");
					this.OnstanowiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_urodzenia", DbType="Date NOT NULL")]
		public System.DateTime data_urodzenia
		{
			get
			{
				return this._data_urodzenia;
			}
			set
			{
				if ((this._data_urodzenia != value))
				{
					this.Ondata_urodzeniaChanging(value);
					this.SendPropertyChanging();
					this._data_urodzenia = value;
					this.SendPropertyChanged("data_urodzenia");
					this.Ondata_urodzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lokalizacja", DbType="VarChar(MAX)", CanBeNull=false)]
		public string lokalizacja
		{
			get
			{
				return this._lokalizacja;
			}
			set
			{
				if ((this._lokalizacja != value))
				{
					this.OnlokalizacjaChanging(value);
					this.SendPropertyChanging();
					this._lokalizacja = value;
					this.SendPropertyChanged("lokalizacja");
					this.OnlokalizacjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="VarChar(15)")]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_przyjecia", DbType="Date NOT NULL")]
		public System.DateTime data_przyjecia
		{
			get
			{
				return this._data_przyjecia;
			}
			set
			{
				if ((this._data_przyjecia != value))
				{
					this.Ondata_przyjeciaChanging(value);
					this.SendPropertyChanging();
					this._data_przyjecia = value;
					this.SendPropertyChanged("data_przyjecia");
					this.Ondata_przyjeciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="stanowisko_pracownik", Storage="_stanowisko1", ThisKey="stanowisko", OtherKey="id_stanowisko", IsForeignKey=true)]
		public stanowisko stanowisko1
		{
			get
			{
				return this._stanowisko1.Entity;
			}
			set
			{
				stanowisko previousValue = this._stanowisko1.Entity;
				if (((previousValue != value) 
							|| (this._stanowisko1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._stanowisko1.Entity = null;
						previousValue.pracowniks.Remove(this);
					}
					this._stanowisko1.Entity = value;
					if ((value != null))
					{
						value.pracowniks.Add(this);
						this._stanowisko = value.id_stanowisko;
					}
					else
					{
						this._stanowisko = default(int);
					}
					this.SendPropertyChanged("stanowisko1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stanowisko")]
	public partial class stanowisko : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_stanowisko;
		
		private string _nazwa;
		
		private decimal _pensja;
		
		private EntitySet<pracownik> _pracowniks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_stanowiskoChanging(int value);
    partial void Onid_stanowiskoChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void OnpensjaChanging(decimal value);
    partial void OnpensjaChanged();
    #endregion
		
		public stanowisko()
		{
			this._pracowniks = new EntitySet<pracownik>(new Action<pracownik>(this.attach_pracowniks), new Action<pracownik>(this.detach_pracowniks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_stanowisko", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_stanowisko
		{
			get
			{
				return this._id_stanowisko;
			}
			set
			{
				if ((this._id_stanowisko != value))
				{
					this.Onid_stanowiskoChanging(value);
					this.SendPropertyChanging();
					this._id_stanowisko = value;
					this.SendPropertyChanged("id_stanowisko");
					this.Onid_stanowiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pensja", DbType="Money NOT NULL")]
		public decimal pensja
		{
			get
			{
				return this._pensja;
			}
			set
			{
				if ((this._pensja != value))
				{
					this.OnpensjaChanging(value);
					this.SendPropertyChanging();
					this._pensja = value;
					this.SendPropertyChanged("pensja");
					this.OnpensjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="stanowisko_pracownik", Storage="_pracowniks", ThisKey="id_stanowisko", OtherKey="stanowisko")]
		public EntitySet<pracownik> pracowniks
		{
			get
			{
				return this._pracowniks;
			}
			set
			{
				this._pracowniks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pracowniks(pracownik entity)
		{
			this.SendPropertyChanging();
			entity.stanowisko1 = this;
		}
		
		private void detach_pracowniks(pracownik entity)
		{
			this.SendPropertyChanging();
			entity.stanowisko1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zamowienie")]
	public partial class zamowienie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_zamowienie;
		
		private int _id_partia;
		
		private int _gatunek;
		
		private decimal _ilosc;
		
		private System.Nullable<System.DateTime> _data_zamówienia;
		
		private string _realizacja;
		
		private System.Nullable<int> _pracownik;
		
		private System.Nullable<int> _firma;
		
		private System.Nullable<decimal> _wartość;
		
		private System.Nullable<System.DateTime> _data_realizacji;
		
		private EntityRef<partia> _partia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_zamowienieChanging(int value);
    partial void Onid_zamowienieChanged();
    partial void Onid_partiaChanging(int value);
    partial void Onid_partiaChanged();
    partial void OngatunekChanging(int value);
    partial void OngatunekChanged();
    partial void OniloscChanging(decimal value);
    partial void OniloscChanged();
    partial void Ondata_zamówieniaChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_zamówieniaChanged();
    partial void OnrealizacjaChanging(string value);
    partial void OnrealizacjaChanged();
    partial void OnpracownikChanging(System.Nullable<int> value);
    partial void OnpracownikChanged();
    partial void OnfirmaChanging(System.Nullable<int> value);
    partial void OnfirmaChanged();
    partial void OnwartośćChanging(System.Nullable<decimal> value);
    partial void OnwartośćChanged();
    partial void Ondata_realizacjiChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_realizacjiChanged();
    #endregion
		
		public zamowienie()
		{
			this._partia = default(EntityRef<partia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_zamowienie", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_zamowienie
		{
			get
			{
				return this._id_zamowienie;
			}
			set
			{
				if ((this._id_zamowienie != value))
				{
					this.Onid_zamowienieChanging(value);
					this.SendPropertyChanging();
					this._id_zamowienie = value;
					this.SendPropertyChanged("id_zamowienie");
					this.Onid_zamowienieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_partia", DbType="Int NOT NULL")]
		public int id_partia
		{
			get
			{
				return this._id_partia;
			}
			set
			{
				if ((this._id_partia != value))
				{
					this.Onid_partiaChanging(value);
					this.SendPropertyChanging();
					this._id_partia = value;
					this.SendPropertyChanged("id_partia");
					this.Onid_partiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gatunek", DbType="Int NOT NULL")]
		public int gatunek
		{
			get
			{
				return this._gatunek;
			}
			set
			{
				if ((this._gatunek != value))
				{
					this.OngatunekChanging(value);
					this.SendPropertyChanging();
					this._gatunek = value;
					this.SendPropertyChanged("gatunek");
					this.OngatunekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilosc", DbType="Decimal(9,3) NOT NULL")]
		public decimal ilosc
		{
			get
			{
				return this._ilosc;
			}
			set
			{
				if ((this._ilosc != value))
				{
					this.OniloscChanging(value);
					this.SendPropertyChanging();
					this._ilosc = value;
					this.SendPropertyChanged("ilosc");
					this.OniloscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_zamówienia", DbType="Date")]
		public System.Nullable<System.DateTime> data_zamówienia
		{
			get
			{
				return this._data_zamówienia;
			}
			set
			{
				if ((this._data_zamówienia != value))
				{
					this.Ondata_zamówieniaChanging(value);
					this.SendPropertyChanging();
					this._data_zamówienia = value;
					this.SendPropertyChanged("data_zamówienia");
					this.Ondata_zamówieniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_realizacja", DbType="Char(3)")]
		public string realizacja
		{
			get
			{
				return this._realizacja;
			}
			set
			{
				if ((this._realizacja != value))
				{
					this.OnrealizacjaChanging(value);
					this.SendPropertyChanging();
					this._realizacja = value;
					this.SendPropertyChanged("realizacja");
					this.OnrealizacjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pracownik", DbType="Int")]
		public System.Nullable<int> pracownik
		{
			get
			{
				return this._pracownik;
			}
			set
			{
				if ((this._pracownik != value))
				{
					this.OnpracownikChanging(value);
					this.SendPropertyChanging();
					this._pracownik = value;
					this.SendPropertyChanged("pracownik");
					this.OnpracownikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firma", DbType="Int")]
		public System.Nullable<int> firma
		{
			get
			{
				return this._firma;
			}
			set
			{
				if ((this._firma != value))
				{
					this.OnfirmaChanging(value);
					this.SendPropertyChanging();
					this._firma = value;
					this.SendPropertyChanged("firma");
					this.OnfirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wartość", DbType="Money")]
		public System.Nullable<decimal> wartość
		{
			get
			{
				return this._wartość;
			}
			set
			{
				if ((this._wartość != value))
				{
					this.OnwartośćChanging(value);
					this.SendPropertyChanging();
					this._wartość = value;
					this.SendPropertyChanged("wartość");
					this.OnwartośćChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_realizacji", DbType="Date")]
		public System.Nullable<System.DateTime> data_realizacji
		{
			get
			{
				return this._data_realizacji;
			}
			set
			{
				if ((this._data_realizacji != value))
				{
					this.Ondata_realizacjiChanging(value);
					this.SendPropertyChanging();
					this._data_realizacji = value;
					this.SendPropertyChanged("data_realizacji");
					this.Ondata_realizacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="zamowienie_partia", Storage="_partia", ThisKey="id_zamowienie", OtherKey="id_partii", IsUnique=true, IsForeignKey=false)]
		public partia partia
		{
			get
			{
				return this._partia.Entity;
			}
			set
			{
				partia previousValue = this._partia.Entity;
				if (((previousValue != value) 
							|| (this._partia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._partia.Entity = null;
						previousValue.zamowienie = null;
					}
					this._partia.Entity = value;
					if ((value != null))
					{
						value.zamowienie = this;
					}
					this.SendPropertyChanged("partia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zwierze_gatunek")]
	public partial class zwierze_gatunek : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_gatunek;
		
		private string _nazwa;
		
		private EntityRef<zwierzyna> _zwierzyna;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_gatunekChanging(int value);
    partial void Onid_gatunekChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    #endregion
		
		public zwierze_gatunek()
		{
			this._zwierzyna = default(EntityRef<zwierzyna>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_gatunek", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_gatunek
		{
			get
			{
				return this._id_gatunek;
			}
			set
			{
				if ((this._id_gatunek != value))
				{
					if (this._zwierzyna.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_gatunekChanging(value);
					this.SendPropertyChanging();
					this._id_gatunek = value;
					this.SendPropertyChanged("id_gatunek");
					this.Onid_gatunekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="zwierzyna_zwierze_gatunek", Storage="_zwierzyna", ThisKey="id_gatunek", OtherKey="id_zwierzyna", IsForeignKey=true)]
		public zwierzyna zwierzyna
		{
			get
			{
				return this._zwierzyna.Entity;
			}
			set
			{
				zwierzyna previousValue = this._zwierzyna.Entity;
				if (((previousValue != value) 
							|| (this._zwierzyna.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._zwierzyna.Entity = null;
						previousValue.zwierze_gatunek = null;
					}
					this._zwierzyna.Entity = value;
					if ((value != null))
					{
						value.zwierze_gatunek = this;
						this._id_gatunek = value.id_zwierzyna;
					}
					else
					{
						this._id_gatunek = default(int);
					}
					this.SendPropertyChanged("zwierzyna");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zwierze_rodzaje_miesa")]
	public partial class zwierze_rodzaje_miesa
	{
		
		private int _id_zwierzyna;
		
		private int _id_gatunek;
		
		private decimal _ile_miesa_gatunku;
		
		public zwierze_rodzaje_miesa()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_zwierzyna", DbType="Int NOT NULL")]
		public int id_zwierzyna
		{
			get
			{
				return this._id_zwierzyna;
			}
			set
			{
				if ((this._id_zwierzyna != value))
				{
					this._id_zwierzyna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_gatunek", DbType="Int NOT NULL")]
		public int id_gatunek
		{
			get
			{
				return this._id_gatunek;
			}
			set
			{
				if ((this._id_gatunek != value))
				{
					this._id_gatunek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ile_miesa_gatunku", DbType="Decimal(9,3) NOT NULL")]
		public decimal ile_miesa_gatunku
		{
			get
			{
				return this._ile_miesa_gatunku;
			}
			set
			{
				if ((this._ile_miesa_gatunku != value))
				{
					this._ile_miesa_gatunku = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.zwierzyna")]
	public partial class zwierzyna : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_zwierzyna;
		
		private string _nazwa;
		
		private int _id_gatunek;
		
		private System.Nullable<decimal> _cena_za_kg;
		
		private EntitySet<inwentarz> _inwentarzs;
		
		private EntityRef<zwierze_gatunek> _zwierze_gatunek;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_zwierzynaChanging(int value);
    partial void Onid_zwierzynaChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void Onid_gatunekChanging(int value);
    partial void Onid_gatunekChanged();
    partial void Oncena_za_kgChanging(System.Nullable<decimal> value);
    partial void Oncena_za_kgChanged();
    #endregion
		
		public zwierzyna()
		{
			this._inwentarzs = new EntitySet<inwentarz>(new Action<inwentarz>(this.attach_inwentarzs), new Action<inwentarz>(this.detach_inwentarzs));
			this._zwierze_gatunek = default(EntityRef<zwierze_gatunek>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_zwierzyna", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_zwierzyna
		{
			get
			{
				return this._id_zwierzyna;
			}
			set
			{
				if ((this._id_zwierzyna != value))
				{
					this.Onid_zwierzynaChanging(value);
					this.SendPropertyChanging();
					this._id_zwierzyna = value;
					this.SendPropertyChanged("id_zwierzyna");
					this.Onid_zwierzynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_gatunek", DbType="Int NOT NULL")]
		public int id_gatunek
		{
			get
			{
				return this._id_gatunek;
			}
			set
			{
				if ((this._id_gatunek != value))
				{
					this.Onid_gatunekChanging(value);
					this.SendPropertyChanging();
					this._id_gatunek = value;
					this.SendPropertyChanged("id_gatunek");
					this.Onid_gatunekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cena_za_kg", DbType="Money")]
		public System.Nullable<decimal> cena_za_kg
		{
			get
			{
				return this._cena_za_kg;
			}
			set
			{
				if ((this._cena_za_kg != value))
				{
					this.Oncena_za_kgChanging(value);
					this.SendPropertyChanging();
					this._cena_za_kg = value;
					this.SendPropertyChanged("cena_za_kg");
					this.Oncena_za_kgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="zwierzyna_inwentarz", Storage="_inwentarzs", ThisKey="id_zwierzyna", OtherKey="zwierzyna")]
		public EntitySet<inwentarz> inwentarzs
		{
			get
			{
				return this._inwentarzs;
			}
			set
			{
				this._inwentarzs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="zwierzyna_zwierze_gatunek", Storage="_zwierze_gatunek", ThisKey="id_zwierzyna", OtherKey="id_gatunek", IsUnique=true, IsForeignKey=false)]
		public zwierze_gatunek zwierze_gatunek
		{
			get
			{
				return this._zwierze_gatunek.Entity;
			}
			set
			{
				zwierze_gatunek previousValue = this._zwierze_gatunek.Entity;
				if (((previousValue != value) 
							|| (this._zwierze_gatunek.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._zwierze_gatunek.Entity = null;
						previousValue.zwierzyna = null;
					}
					this._zwierze_gatunek.Entity = value;
					if ((value != null))
					{
						value.zwierzyna = this;
					}
					this.SendPropertyChanged("zwierze_gatunek");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_inwentarzs(inwentarz entity)
		{
			this.SendPropertyChanging();
			entity.zwierzyna1 = this;
		}
		
		private void detach_inwentarzs(inwentarz entity)
		{
			this.SendPropertyChanging();
			entity.zwierzyna1 = null;
		}
	}
}
#pragma warning restore 1591
